[ci/cd] Added Code Coverage

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -73,6 +73,9 @@ jobs:
           --verbosity normal \
           --logger "console;verbosity=detailed" \
           --logger "trx;LogFileName=smoke-test-results.trx"
+          --collect:"XPlat Code Coverage" \
+          --results-directory ./TestResults \
+          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*Tests*]*"
 
       - name: Загружаем результаты тестов как артефакты
         uses: actions/upload-artifact@v4
@@ -89,6 +92,14 @@ jobs:
           name: Smoke Tests Results
           path: '**/TestResults/*.trx'
           reporter: dotnet-trx
+
+      - name: Сохраняем артефакты отчёта по покрытию Smoke
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: coverage-smoke # Имя должно начинаться с coverage-
+          path: '**/TestResults/**/coverage.cobertura.xml'
+          retention-days: 1
 
   run-xunit-tests:
     needs: build-app
@@ -131,30 +142,38 @@ jobs:
           path: '**/TestResults/*.trx'
           reporter: dotnet-trx
 
-      - name: Очищаем дубликты отчетов покрытия (папки созданные VSTest), чтобы остались только папки созданные Coverlet
-        if: always()
-        run: rm -rf ./TestResults/_* 
-
-      - name: Вычисляем покрытие тестами
-        uses: irongut/CodeCoverageSummary@v1.3.0
+      - name: Сохраняем артефакты отчёта по покрытию XUnit
+        uses: actions/upload-artifact@v4
         if: always()
         with:
-          filename: './TestResults/**/coverage.cobertura.xml'
-          badge: true
-          format: markdown
-          output: both
-          thresholds: '40 75'
-          fail_below_min: true  
+          name: coverage-xunit # Имя должно начинаться с coverage-
+          path: '**/TestResults/**/coverage.cobertura.xml'
+          retention-days: 1
 
-      - name: Выводим Summary
-        if: always()
-        run: |
-          ls -R ./TestResults # Для отладки смотрим содержимое папки
-          if [ -f code-coverage-results.md ]; then
-            cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
-          else
-            echo "Файл покрытия не найден" >> $GITHUB_STEP_SUMMARY
-          fi
+      # - name: Очищаем дубликты отчетов покрытия (папки созданные VSTest), чтобы остались только папки созданные Coverlet
+      #   if: always()
+      #   run: rm -rf ./TestResults/_* 
+
+      # - name: Вычисляем покрытие тестами
+      #   uses: irongut/CodeCoverageSummary@v1.3.0
+      #   if: always()
+      #   with:
+      #     filename: './TestResults/**/coverage.cobertura.xml'
+      #     badge: true
+      #     format: markdown
+      #     output: both
+      #     thresholds: '40 75'
+      #     fail_below_min: true  
+
+      # - name: Выводим Summary
+      #   if: always()
+      #   run: |
+      #     ls -R ./TestResults # Для отладки смотрим содержимое папки
+      #     if [ -f code-coverage-results.md ]; then
+      #       cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+      #     else
+      #       echo "Файл покрытия не найден" >> $GITHUB_STEP_SUMMARY
+      #     fi
 
   run-nunit-tests:
     needs: build-app
@@ -276,7 +295,21 @@ jobs:
             -reporttypes:"Cobertura;MarkdownSummaryGitHub"
 
       - name: Выводим Summary
-        run: cat merged-reports/SummaryGitHub.md >> $GITHUB_STEP_SUMMARY
+        run: |
+          # Для отладки смотрим содержимое папки
+          if [ -d "./merged-reports" ]; then
+            ls -R ./merged-reports
+          else
+            echo "Директория merged-reports не найдена!"
+            exit 1
+          fi
+          # Проверяем наличие файла перед cat, чтобы джоба не падала
+          if [ -f merged-reports/SummaryGitHub.md ]; then
+            cat merged-reports/SummaryGitHub.md >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Итоговый отчет не сформирован" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
       - name: Сохраняем объединённый отчёт о покрытии
         uses: actions/upload-artifact@v4
